Updated documentation comments
VedantParanjape/esp-wifi-logger pull request #18
Opened 2024-10-27 02:23 UTC by JerelJr

In reference to #3.

- Moved function description comments to header files
- Corrected `tcp_network_manager` description; return type is bool not void
- Regenerated documentation

2024-10-27 03:42 UTC, VedantParanjape commented
Hey Thanks for the PR. Can you remove the generated html files? I will handle that on end!

2024-10-27 05:48 UTC, JerelJr commented
Can do!

2024-11-04 16:12 UTC, VedantParanjape commented
Hey there are still changes in docs folder.

2024-11-05 00:13 UTC, JerelJr commented
My mistake. I thought you only wanted the HTML files removed

2024-11-08 21:25 UTC, VedantParanjape commented
Hey, I think you messed up the commit, you need to roll back the commit and then just add the header changes to the commit. Now it seems you deleted the complete doc folder in your repo.

2024-11-09 02:08 UTC, JerelJr commented
Ah my mistake. Will fix.

2024-11-19 13:58 UTC, VedantParanjape requested changes

2024-11-19 13:58 UTC, VedantParanjape commented on include/utils.h
> -#endif
can you add back the new line?

2024-11-19 13:58 UTC, VedantParanjape commented on include/wifi_logger.h
> -
this as well.

2024-11-19 13:58 UTC, VedantParanjape commented on utils.cpp
> -}
this as well.

2024-11-20 01:28 UTC, JerelJr commented
Just for clarity, you want me to add a new line to the end of each of those files, correct?

2024-11-22 19:38 UTC, VedantParanjape commented
> Just for clarity, you want me to add a new line to the end of each of those files, correct?

yeah, correct, undo the changes basically.

2024-12-14 16:49 UTC, VedantParanjape commented
ping

2025-02-15 22:10 UTC, JerelJr commented
Sorry for the delay. I added the newlines.

2025-04-24 22:25 UTC, merged